import 'package:flutter/material.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina2widget/generated/GeneratedImage4Widget.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina2widget/generated/GeneratedInput2Widget.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina2widget/generated/GeneratedImage2Widget.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina2widget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina2widget/generated/GeneratedGroup4Widget1.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina2widget/generated/GeneratedImage3Widget.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina2widget/generated/GeneratedPuedesbuscararticulosounareferenciaennuestrocatalogodal.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina2widget/generated/GeneratedIniciasesionoregistrateparapodercomenzarausarnuestraapl.dart';

/* Frame Pagina 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPagina2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 86, 204, 242),
                ),
              ),
              Positioned(
                left: -30.0,
                top: -14.0,
                right: null,
                bottom: null,
                width: 458.0,
                height: 933.0,
                child: GeneratedImage4Widget(),
              ),
              Positioned(
                left: 60.0,
                top: 203.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 90.0,
                child:
                    GeneratedIniciasesionoregistrateparapodercomenzarausarnuestraapl(),
              ),
              Positioned(
                left: 10.0,
                top: 381.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 60.0,
                child: GeneratedInput2Widget(),
              ),
              Positioned(
                left: 256.0,
                top: 381.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 60.0,
                child: GeneratedGroup4Widget1(),
              ),
              Positioned(
                left: -13.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 195.0,
                height: 111.0,
                child: GeneratedImage2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 111.0,
                child: GeneratedImage3Widget(),
              ),
              Positioned(
                left: 64.0,
                top: 487.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 174.0,
                child:
                    GeneratedPuedesbuscararticulosounareferenciaennuestrocatalogodal(),
              ),
              Positioned(
                left: 127.0,
                top: 669.0,
                right: null,
                bottom: null,
                width: 154.0,
                height: 55.0,
                child: GeneratedGroup5Widget(),
              )
            ]),
      ),
    ));
  }
}
