import 'package:flutter/material.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina5widget/generated/GeneratedCrearunacuentaWidget.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina5widget/generated/GeneratedContrasenaWidget1.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina5widget/generated/GeneratedContrasenaWidget2.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina5widget/generated/GeneratedImage3Widget3.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina5widget/generated/GeneratedSquareoutlineWidget3.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina5widget/generated/GeneratedInput2Widget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina5widget/generated/GeneratedImage9Widget.dart';

/* Frame Pagina 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPagina5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 86, 204, 242),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.1618357487922706;

                  final double height = constraints.maxHeight;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.45652173913043476,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedImage9Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 111.0,
                child: GeneratedImage3Widget3(),
              ),
              Positioned(
                left: 78.0,
                top: 251.0,
                right: null,
                bottom: null,
                width: 260.0,
                height: 37.0,
                child: GeneratedCrearunacuentaWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 495.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 55.0,
                child: GeneratedContrasenaWidget1(),
              ),
              Positioned(
                left: 31.0,
                top: 582.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 55.0,
                child: GeneratedContrasenaWidget2(),
              ),
              Positioned(
                left: 36.0,
                top: 683.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedSquareoutlineWidget3(),
              ),
              Positioned(
                left: 128.0,
                top: 756.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedInput2Widget2(),
              )
            ]),
      ),
    ));
  }
}
