import 'package:flutter/material.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina4widget/generated/GeneratedImage3Widget2.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina4widget/generated/GeneratedContrasenaWidget.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina4widget/generated/GeneratedIniciarsesionWidget.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina4widget/generated/GeneratedEstasdeacuerdoconlosterminosycondicionesestablecidospor.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina4widget/generated/GeneratedInput2Widget1.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina4widget/generated/GeneratedSquareoutlineWidget.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina4widget/generated/GeneratedCreaunacuentaWidget1.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina4widget/generated/GeneratedTodavianotienescuentaWidget.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina4widget/generated/GeneratedCorreoWidget.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina4widget/generated/GeneratedSquareoutlineWidget2.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina4widget/generated/GeneratedSquareoutlineWidget1.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina4widget/generated/GeneratedImage8Widget.dart';

/* Frame Pagina 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPagina4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 86, 204, 242),
                ),
              ),
              Positioned(
                left: -68.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 516.0,
                height: 918.0,
                child: GeneratedImage8Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 111.0,
                child: GeneratedImage3Widget2(),
              ),
              Positioned(
                left: 98.0,
                top: 256.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 37.0,
                child: GeneratedIniciarsesionWidget(),
              ),
              Positioned(
                left: 72.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 252.0,
                height: 29.0,
                child: GeneratedTodavianotienescuentaWidget(),
              ),
              Positioned(
                left: 139.0,
                top: 787.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 20.0,
                child: GeneratedCreaunacuentaWidget1(),
              ),
              Positioned(
                left: 122.0,
                top: 615.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedInput2Widget1(),
              ),
              Positioned(
                left: 40.0,
                top: 545.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedSquareoutlineWidget(),
              ),
              Positioned(
                left: 357.0,
                top: 453.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedSquareoutlineWidget1(),
              ),
              Positioned(
                left: 357.0,
                top: 453.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedSquareoutlineWidget2(),
              ),
              Positioned(
                left: 79.0,
                top: 538.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 44.0,
                child:
                    GeneratedEstasdeacuerdoconlosterminosycondicionesestablecidospor(),
              ),
              Positioned(
                left: 28.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 55.0,
                child: GeneratedContrasenaWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 55.0,
                child: GeneratedCorreoWidget(),
              )
            ]),
      ),
    ));
  }
}
