import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/svg/svg.dart';

/* Vector Rectangle 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Opacity(
      opacity: 0.8999999761581421,
      child: Container(
        width: 431.0,
        height: 0.0,
        child: SvgWidget(painters: [
          SvgPathPainter.fill()..color = Color.fromARGB(255, 242, 242, 242),
        ]),
      ),
    ));
  }
}
