import 'package:flutter/material.dart';
import 'package:flutterapp/act8_android_finalapp/generatedcorreowidget1/generated/GeneratedRectangle8Widget4.dart';
import 'package:flutterapp/act8_android_finalapp/generatedcorreowidget1/generated/GeneratedNombredeusuarioWidget.dart';

/* Group Correo
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCorreoWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 351.0,
      height: 55.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 351.0,
              height: 55.0,
              child: GeneratedRectangle8Widget4(),
            ),
            Positioned(
              left: 14.0,
              top: 17.0,
              right: null,
              bottom: null,
              width: 164.0,
              height: 22.0,
              child: GeneratedNombredeusuarioWidget(),
            )
          ]),
    ));
  }
}
