import 'package:flutter/material.dart';
import 'package:flutterapp/act8_android_finalapp/generatedcorreowidget2/generated/GeneratedRectangle8Widget5.dart';
import 'package:flutterapp/act8_android_finalapp/generatedcorreowidget2/generated/GeneratedCorreoelectronicoWidget.dart';

/* Group Correo
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCorreoWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 351.0,
      height: 59.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 351.0,
              height: 59.0,
              child: GeneratedRectangle8Widget5(),
            ),
            Positioned(
              left: 21.0,
              top: 18.236364364624023,
              right: null,
              bottom: null,
              width: 231.0,
              height: 23.454545974731445,
              child: GeneratedCorreoelectronicoWidget(),
            )
          ]),
    ));
  }
}
