import 'package:flutter/material.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina1widget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina1widget/generated/GeneratedImage1Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina1widget/generated/GeneratedBienvenidosalConsultorioDentalvitrualaquipodrasrealizar.dart';

/* Frame Pagina 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPagina1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: TransformHelper.rotate(
            a: 1.00,
            b: 0.00,
            c: -0.00,
            d: 1.00,
            child: ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                width: 414.0,
                height: 896.0,
                child: Stack(
                    fit: StackFit.expand,
                    alignment: Alignment.center,
                    overflow: Overflow.visible,
                    children: [
                      ClipRRect(
                        borderRadius: BorderRadius.zero,
                        child: Container(
                          color: Color.fromARGB(255, 114, 246, 206),
                        ),
                      ),
                      Positioned(
                        left: -4.4970221519470215,
                        top: -1.709936261177063,
                        right: null,
                        bottom: null,
                        width: 435.0,
                        height: 921.0,
                        child: GeneratedImage1Widget(),
                      ),
                      Positioned(
                        left: 25.26533317565918,
                        top: 69.39000701904297,
                        right: null,
                        bottom: null,
                        width: 352.0,
                        height: 218.0,
                        child:
                            GeneratedBienvenidosalConsultorioDentalvitrualaquipodrasrealizar(),
                      ),
                      Positioned(
                        left: 131.428466796875,
                        top: 618.7481689453125,
                        right: null,
                        bottom: null,
                        width: 150.0,
                        height: 50.0,
                        child: GeneratedGroup4Widget(),
                      )
                    ]),
              ),
            )));
  }
}
