import 'package:flutter/material.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina3widget/generated/GeneratedRectangle6Widget3.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina3widget/generated/GeneratedSillasWidget4.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina3widget/generated/GeneratedImage7Widget.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina3widget/generated/GeneratedSillasWidget1.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina3widget/generated/GeneratedSillasWidget2.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina3widget/generated/GeneratedImage6Widget.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina3widget/generated/GeneratedSillasWidget3.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina3widget/generated/GeneratedCatalogoWidget1.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina3widget/generated/GeneratedImage3Widget1.dart';
import 'package:flutterapp/act8_android_finalapp/generatedpagina3widget/generated/GeneratedSillasWidget.dart';

/* Frame Pagina 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPagina3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 86, 204, 242),
                ),
              ),
              Positioned(
                left: -21.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 459.0,
                height: 897.0,
                child: GeneratedImage7Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 111.0,
                child: GeneratedImage3Widget1(),
              ),
              Positioned(
                left: 178.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 195.0,
                height: 77.0,
                child: GeneratedCatalogoWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 225.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 166.0,
                child: GeneratedSillasWidget(),
              ),
              Positioned(
                left: 217.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 166.0,
                child: GeneratedSillasWidget1(),
              ),
              Positioned(
                left: 49.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 166.0,
                child: GeneratedSillasWidget2(),
              ),
              Positioned(
                left: 1.0,
                top: 511.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 176.0,
                child: GeneratedRectangle6Widget3(),
              ),
              Positioned(
                left: 150.0,
                top: 225.0,
                right: null,
                bottom: null,
                width: 114.0,
                height: 166.0,
                child: GeneratedSillasWidget3(),
              ),
              Positioned(
                left: 301.0,
                top: 225.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 166.00001525878906,
                child: GeneratedSillasWidget4(),
              ),
              Positioned(
                left: 54.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 103.0,
                child: GeneratedImage6Widget(),
              )
            ]),
      ),
    ));
  }
}
